### ISSUE TITLE
Project rename

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-job-registry-elastic-api#1]
In internal discussions there was some confusion about the position/role of this project, as we already have a component called "job tracker"  . The responsibilities would be more clear if this project ("openeo-job-tracker-elastic-api" at the moment)  would use the term "registry" instead of "tracker" as this component is more about pure storage of the job status than actually doing active tracking (status polling, event handling, etc.)

How feasible is it to do this rename? For example, including:
- [x] rename/migrate git repo to `openeo-job-registry-elastic-api`
- [x] rename url of VITO instance to  `jobregistry.openeo....`

If too much of a hassle, we can keep things as is and just make sure things are documented clearly enough. But I guess if it makes sense to do a rename, we better do it now at this stage before we start rolling it out to dev/prod.

**Comment by JanssenBrm** [comment]
The rename shouldn't be too much work. If we want to implement https://github.com/Open-EO/openeo-job-tracker-elastic-api/issues/7 , we need to do changes on the hosting level anyway. As this is managed by VITO INF, we can also request a new URL. The only catch is that the domain can not be equal to `vgt.vito.be`, but it would end up like `jobregistry.openeo.vito.be`. If that is OK, we can proceed with both the renaming and HTTPS switch at the same time.

**Comment by soxofaan** [comment]
also:
- [ ] rename OIDC client in keycloak.  e.g. "openeo-elastic-job-registry"

**Comment by JanssenBrm** [comment]
Requested updated URL at VITO INF, including the HTTPS setup and HA (#9)

**Comment by JanssenBrm** [comment]
Updated the name of the oidc client in Keycloak

**Comment by JanssenBrm** [comment]
The renaming should be complete now:

- Updated the name of the git repo
- New (HTTPS, #7) URL has been set up: https://jobregistry.openeo.vito.be
- Renamed the OIDC client

**Comment by soxofaan** [comment]
great, thanks.

another place where I found the old name: secret vault path still contains `openeo-job-tracker-elastic-api`

**Comment by soxofaan** [comment]
I updated the path in vault too now
