### ISSUE TITLE
backend_id on PATCH /jobs

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-job-registry-elastic-api#16]
I just noticed that "backend_id" is a required field on `PATCH /job`

```
openeo_driver.jobregistry.EjrError: EJR API error: 
400 'Bad Request' on `PATCH 'https://jobregistry.openeo.vito.be/jobs'`: 
{"statusCode":400,"message":["backend_id should not be empty"],"error":"Bad Request"}
```

It should indeed be required for creating a job (`POST /jobs`), 
but it should actually be forbidden when patching job metadata.
There are actually a couple of more fields that are required when created, but should never be altered later
The most important ones:
- job_id (obviously)
- backend_id
- parent_id (not really required, null by default, but should not be altered after creation)
- user_id

**Comment by JanssenBrm** [comment]
Thanks for the feedback! I've updated the code to have a more strict policy on checking the input data.

**Comment by JanssenBrm** [comment]
v1.13.0 is now deployed and can be tested

**Comment by soxofaan** [comment]
thanks!
