### ISSUE TITLE
Field duplication for job start and end timestamps

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-job-registry-elastic-api#2]
https://github.com/Open-EO/openeo-job-tracker-elastic-api/blob/f2590099f7ed190fef65ca216b52632ae1abc6c2/src/jobs/models/job.dto.ts#L145-L175

There seem to be duplication between job metadata fields `started` vs `start_datetime`  and `finished` vs `end_datetime`

@bossie  you added `start_datetime` and `end_datetime` at https://github.com/Open-EO/openeo-python-driver/blob/07a5daed38ae18207c9b963888c5782bfd5f3ef4/openeo_driver/backend.py#L277-L278  in https://github.com/Open-EO/openeo-python-driver/commit/0cd9eed2531427bc0af5adc8fd00b9974f75141a
do you remember what the goal of these is is? Is this duplication, or is there a separate use for these fields?

**Comment by m-mohr** [comment]
fwiw: start_datetime and end_datetime are names from STAC for the data (capture times, not the processing start and end) so there's a difference, but not sure whether it's useful in this context.

**Comment by bossie** [comment]
Indeed, `start_datetime` and `end_datetime` have to do with [STAC](https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md#date-and-time-range), whereas `started` and `finished` determine [usage/duration of a batch job](https://openeo.org/documentation/1.0/developers/api/reference.html#tag/Data-Processing/operation/describe-job).

**Comment by soxofaan** [comment]
So the confusion is that `started` and `finished` is batch job metadata, while `start_datetime` and `end_datetime` (and some other fields as well I guess) is metadata of the batch job _result_.
I think it will be cleaner to have better separation  here.

I'd propose to just define a `result_metadata` (toplevel) field that replaces the current toplevel fields:
- `start_datetime`
- `end_datetime`
- `geometry`
- `bbox`
- `area`
- `epsg`
- `instruments`
- `processing_facility`
- `processing_software`

And while we're at it, I think that
- `memory_time_megabyte_seconds`
- `cpu_time_seconds`
can also be dropped because that should be covered under `usage` (field that already exists)

**Comment by soxofaan** [comment]
and like with `process` and `job_options` in #4, I think these fields `result_metadata` and `usage` should not be indexed/searchable, just visible in kibana

**Comment by JanssenBrm** [comment]
Thanks for the updates! Do you also want us to update (remove properties) the existing records in the database?

**Comment by soxofaan** [comment]
It's fine to leave the existing records as-is

**Comment by soxofaan** [comment]
I think we can close this ticket for now (there are probably some other fields to reconsider, but that's for another ticker/PR)
