### ISSUE TITLE
add costs field

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-job-registry-elastic-api#29]
Please add a top-level `costs` field (= job cost in credits) to the job entity.

Context: https://github.com/Open-EO/openeo-geopyspark-driver/issues/632

**Comment by JanssenBrm** [comment]
Do we need to mark this as a  required field or do we need to keep the flexibility of allowing empty values?

**Comment by bossie** [comment]
_Not_ required because we send PATCH requests without it, for all kinds of things.

**Comment by JanssenBrm** [comment]
Version 1.19.0 deployed (https://jobregistry.openeo.vito.be/docs)
