### ISSUE TITLE
no (timely) response from API

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-job-registry-elastic-api#33]
[Latest integration tests run of OpenEO](https://jenkins.vgt.vito.be/job/openEO/job/openeo-integrationtests/2265/) shows quite a few failures that have to do with the prod API not returning a response within the read timeout of 20 seconds.

In particular there are some read timed outs and some disconnects, mostly on search queries but also when creating and updating a job :

```
r-2401254795584aca8621e4cc3d29dd8d: Read timed out. on POST /jobs/search
r-240125a1f797479398671934b0eefc8e: Remote end closed connection without response on POST /jobs/search
r-24012521290f41868c2d1160ce5b0690: Remote end closed connection without response on POST /jobs/search
r-2401252d438a47b1b4047577e92ce4c1: Remote end closed connection without response on PATCH /jobs/j-240125e5f2ca45e3beb82cc5ee8b992e
r-24012590735346af92b82958f276a230: Read timed out. on POST /jobs
r-24012597482742589057a2ad10d03d6c: Read timed out. on POST /jobs/search
r-240125e457fb4a8893b1379f742ac93d: Remote end closed connection without response on POST /jobs/search
r-2401254c70c443ee83721f0efe19f25a: Read timed out. on POST /jobs/search
```

OpenEO logs in Kibana contain the details (filter on `req_id`s from above).

https://kibana-infra.vgt.vito.be/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-24T23:00:00.000Z',to:'2024-01-25T23:00:00.000Z'))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'907d8590-4f1b-11ed-8cc4-3747d5233c59',key:req_id,negate:!f,params:(query:r-24012590735346af92b82958f276a230),type:phrase),query:(match:(req_id:(query:r-24012590735346af92b82958f276a230,type:phrase))))),index:'907d8590-4f1b-11ed-8cc4-3747d5233c59',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

**Comment by bossie** [comment]
@JanssenBrm did you have a chance to look into this issue yet? It will become a blocker for new OpenEO releases.

We considered a workaround in the form of a retry but deemed it unfeasible because it also happens upon saving a new job and we think that will introduce duplicates.

**Comment by JanssenBrm** [comment]
Yes we are looking into it. First analysis:
* There are no clear indications of an error that could indicate no timely response. 
* There are quite a lot of authentication errors so we've added logging to get more information.
* With some testing, I noticed an increasing time to store documents. The code was build to receive jobs in bulk using the ES Bulk API, but the APIs only support storing single documents. After changing to the ES Index API, the storage of the documents seems to be much quicker.

My first guess would be that we are running into limitations outside of the application scope. However, it make sense to run the tests again with the latest improvements.

**Comment by bossie** [comment]
> * There are quite a lot of authentication errors so we've added logging to get more information.

These authentication errors don't seem to reach OpenEO so my guess would be that they are being retried in your API; could this account for some delay?

> * With some testing, I noticed an increasing time to store documents. The code was build to receive jobs in bulk using the ES Bulk API, but the APIs only support storing single documents. After changing to the ES Index API, the storage of the documents seems to be much quicker.

Ok, I suppose that will speed up insert but not search. I ran some queries in the meanwhile (by `job_id` + `backend_id`) and they're still in the order of several seconds, with an outlier of more than 7 seconds. With my limited knowledge of ES I can only confirm that mapping type `keyword` and query filter `term` are indeed the way to go.

> My first guess would be that we are running into limitations outside of the application scope.

As in: ES itself? Or related to authentication perhaps?

**Comment by bossie** [comment]
An integration test (ran against the jobregistry API without the bulk insert) that attempted to insert a job failed because of a read timed out:

https://kibana-infra.vgt.vito.be/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-25T23:00:00.000Z',to:'2024-01-26T23:00:00.000Z'))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'907d8590-4f1b-11ed-8cc4-3747d5233c59',key:req_id,negate:!f,params:(query:r-240126830686471cbce2d4071807f69b),type:phrase),query:(match:(req_id:(query:r-240126830686471cbce2d4071807f69b,type:phrase))))),index:'907d8590-4f1b-11ed-8cc4-3747d5233c59',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

The job was inserted in ES:

https://kibana-apps.vgt.vito.be/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-25T23:00:00.000Z',to:'2024-01-26T23:00:00.000Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:adb8fca0-bb55-11ee-9c26-3f76720e6a27,key:job_id,negate:!f,params:(query:j-240126323ab843a396fbb118784b3818),type:phrase),query:(match:(job_id:(query:j-240126323ab843a396fbb118784b3818,type:phrase))))),index:adb8fca0-bb55-11ee-9c26-3f76720e6a27,interval:auto,query:(language:lucene,query:''),sort:!(!(created,desc)))

Maybe there's some logging in the API that tells you how long it took ES to insert this document and offer a clue as to where the delay might be (is it also > 20 seconds or much less?).

**Comment by bossie** [comment]
> Sorry to pick this up again here as the issue on the timeouts is probably not related to implementation of the EJR but to throughput issues on the level of the F5. I've checked with the INF team and apparently the throughput of the traffic is reaching the limits of the F5 license. INF has already increased the flow rate for the EJR URL so hopefully this helps in short term. They are in discussion of increasing the license.

And by throughput you mean number of requests per second? Because the payload is still a bit of plain text and therefore not very big.
