### ISSUE TITLE
Strict typing on `dependencies`

### ISSUE THREAD

**Issue by JanssenBrm** [Open-EO/openeo-job-registry-elastic-api#36]
The typing on the `dependencies` key is too strict, not allowing it to include additional fields. The strict convention is not necessary as the field is also mapped as flattened in ElasticSearch, so there is no need to search for its detailed properties. Additionally, the strict validation requires an update of the code every time a new field is added.

**Comment by JanssenBrm** [comment]
Referring to https://github.com/Open-EO/openeo-geopyspark-driver/issues/786, this is the original ticket where this behaviour was detected.

**Comment by bossie** [comment]
Ok, I was under the impression that this was an issue with the mapping but it's in the application instead.

Thanks for the quick fix.

**Comment by JanssenBrm** [comment]
Indeed I noticed that the application was still applying some typing and validation to the `dependencies` object so I removed the specific typings. I also checked the other fields and they now all either have a basic type (`string`, `number` or `boolean`) or a generic `any` type
