### ISSUE TITLE
add dependency_usage field

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-job-registry-elastic-api#37]
Please add a top-level field called `dependency_usage` to the job entity. It's optional and of type string.

Context: https://github.com/eu-cdse/openeo-cdse-infra/issues/261

Thanks!

**Comment by JanssenBrm** [comment]
@bossie  - Can you also provide some insights if you want this field to be searchable?

**Comment by bossie** [comment]
Not searchable.
