### ISSUE TITLE
ELK indexing of `process` field

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-job-registry-elastic-api#4]
the `process` field is often a large, deep JSON doc and should not be indexed/parsed too much in ES/Kibana.

For example, Kibana is now too enthusiastically parsing all nodes and arguments of the process graphs:
 
![image](https://user-images.githubusercontent.com/44946/204802505-88df036c-44af-4853-97d7-abdd86ab3f94.png)

**Comment by JanssenBrm** [comment]
I've updated the settings in Kibana to not show the process in the reporting

**Comment by soxofaan** [comment]
thanks, a couple of follow up questions:

- the "process" field is now completely hidden in Kibana. Is there a way to just show it as a single text-like blob?
- Also, I think the "job_options" field  should get the same treatment.
- You do these settings manually in the Kibana UI, or is there a pipeline for that?

**Comment by JanssenBrm** [comment]
Updated the mapping in kibana to show the `job_options` and `process` as a serialized string.

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/10883374/207324325-0cbc64b4-c3d4-45af-bca6-334e7be77a1d.png">
